name: mascotas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  equatable: ^2.0.5
  file_picker: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
