name: mascotas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0 <3.22.1"

dependencies:
  build_runner: ^2.4.8
  collection: ^1.18.0
  equatable: ^2.0.5
  file_picker: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_file_downloader: ^1.2.1
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.0.8
  intl: ^0.19.0
  stomp_dart_client: ^2.0.0
  timezone: ^0.9.3

dev_dependencies:
  test: ^1.24.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/icono.png
